import Vue from "vue";
import { installComponents } from "@vusion/utils";
// import * as lcapLogin from "lcap-login/dist-theme";
// import * as lcapEchartsBar from "lcap-echarts-bar/dist-theme";
// import * as uCalendarTable from "u-calendar-table/dist-theme";
// import * as lcapEchartsPie from "lcap-echarts-pie/dist-theme";
// import * as lcapEchartsLine from "lcap-echarts-line/dist-theme";
// installComponents(Vue, lcapLogin);
// installComponents(Vue, lcapEchartsBar);
// installComponents(Vue, uCalendarTable);
// installComponents(Vue, lcapEchartsPie);
// installComponents(Vue, lcapEchartsLine);
